web:
  listen_address: "127.0.0.1:9871"
  metrics_path: "/metrics"

device:
  gateway_address: "powerwall"
  login_email: "powerwalluser@example.com"
  login_password: "Super!Secret!Password"
  tls_cert_file: "/var/lib/prometheus-powerwall-exporter/cert.pem"
  retry_interval: "1s"
  retry_timeout: "60s"
